# Generated by Django 5.1.5 on 2025-01-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '博客类别管理',
                'verbose_name_plural': '博客类别管理',
                'db_table': 't_article_type',
            },
        ),
    ]
