# Generated by Django 5.1.5 on 2025-01-22 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0003_alter_studentinfo_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTypeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookTypeName', models.CharField(db_column='book_type_name', max_length=50)),
            ],
            options={
                'verbose_name': '图书类别信息',
                'db_table': 't_book_type',
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(db_column='book_name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('publishDate', models.DateField(db_column='publish_date')),
                ('bookType', models.ForeignKey(db_column='book_type', on_delete=django.db.models.deletion.PROTECT, to='helloWorld.booktypeinfo')),
            ],
            options={
                'verbose_name': '图书信息',
                'db_table': 't_book',
            },
        ),
    ]
