# Generated by Django 5.1.5 on 2025-01-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0004_booktypeinfo_bookinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('account', models.FloatField()),
            ],
            options={
                'verbose_name': '用户账户信息',
                'db_table': 't_account',
            },
        ),
    ]
